CREATE TABLE TP(numTP VARCHAR(6) NOT NULL, PRIMARY KEY(numTP));

CREATE TABLE Annee(numAnnee INT, PRIMARY KEY(numAnnee));

CREATE TABLE Universite(numUniv INT AUTO_INCREMENT, nomUniv VARCHAR(64) NOT NULL, zimbraUniv VARCHAR(255) NOT NULL, PRIMARY KEY(numUniv));

CREATE TABLE EDT(numTP VARCHAR(6), numAnnee INT, numUniv INT, etupass VARCHAR(64) NOT NULL, nomEDT VARCHAR(64) NOT NULL, PRIMARY KEY(numTP, numAnnee, numUniv), FOREIGN KEY(numTP) REFERENCES TP(numTP), FOREIGN KEY(numAnnee) REFERENCES Annee(numAnnee), FOREIGN KEY(numUniv) REFERENCES Universite(numUniv));
